require 'excon'
require 'json'
require 'simplify_api'

require 'telbe/base'
require 'telbe/contact'
require 'telbe/keyboard'
require 'telbe/inline'
require 'telbe/poll'
require 'telbe/media'
require 'telbe/user'
require 'telbe/sticker'
require 'telbe/location'
require 'telbe/webhook'
require 'telbe/bot'
